### PR TITLE
GH-2588: ARBP support batch recoverable

### LINKED ISSUE #2588: Provide ability to disable/limit retries in batch listener when using DefaultAfterRollbackProcessor
**Expected Behavior**
Configuration to disable/limit retries in the batch listener when using DB transactions and `DefaultAfterRollbackProcessor`
Example of listener `@KafkaListener(topics = BATCH_TOPIC, batch = "true") {}`

**Current Behavior**
Currently, the `DefaultAfterRollbackProcessor` retries the failing message infinitely if using batch listener with DB transactions.

**Context**
The main problem if we forget to handle the failing message inside the listener then the failed message will stuck until we take some manual action to skip this message. That's why we would like to have a config to disable/limit retries at the configurations level.
I tried to find a way to disable retries for batch listeners but unsuccessfully.
`new FixedBackOff(0, 0)`
`new DefaultAfterRollbackProcessor<>(deadLetterPublishingRecoverer, backOff);`

The workaround can be to force to use `recoverable=true` always  in order to limit retries

```
return new DefaultAfterRollbackProcessor<>(deadLetterPublishingRecoverer, backOff) {
            @Override
            public void process(
                    @NotNull List<ConsumerRecord<Object, Object>> consumerRecords,
                    @NotNull org.apache.kafka.clients.consumer.Consumer<Object, Object> consumer,
                    MessageListenerContainer container,
                    @NotNull Exception exception,
                    boolean recoverable,
                    @NotNull ContainerProperties.EOSMode eosMode) {
                // Force all messages to be recoverable.
                super.process(consumerRecords, consumer, container, exception, true, eosMode);
            }
        };
```

### PR DESCRIPTION
**Pull request by Wzy19930507**
Resolves #2588

This is a draft of support DLT batch recover for `DefaultAfterRollbackProcessor`. so we can evaluate if it's going in the right direction before doing a final review, adding docs, etc.

Function
* add opt-in property `batchRecoverAfterRollback` at `ContainerProperties`
* add method processBatch at `AfterRollbackProcessor`

Batch recoverable
* batchRecoverAfterRollback is true
* set transcation DLT to enable isCommitRecovered
* enable kafka transcation

exception handler logic
* in retry, seek to begin
* out of retry exception recover entire recods
* recover fail, seek to begin

### CODE REVIEW

File: spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java [hunk 1]
```diff
@@ -138,7 +141,7 @@ public DefaultAfterRollbackProcessor(@Nullable BiConsumer<ConsumerRecord<?, ?>,
 			BackOff backOff, @Nullable BackOffHandler backOffHandler, @Nullable KafkaOperations<?, ?> kafkaOperations,
 			boolean commitRecovered) {
 
-		super(recoverer, backOff, backOffHandler);
+		super(recoverer, backOff, backOffHandler, null);
```
Comment (Wzy19930507) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java:144]: may be use `CommonLoggingErrorHandler` first

**Comment by garyrussell** [comment]
Can you provide a valid use case where this would be useful? 

Any transactional sends for the records before the failed one would have been rolled back, so it doesn’t make sense to to skip those records on the retry. If you are not doing transactional sends, then why use transactions?

I tried to convey this in my comments on the issue.

**Comment by Wzy19930507** [comment]
> Any transactional sends for the records before the failed one would have been rolled back, so it doesn’t make sense to to skip those records on the retry. If you are not doing transactional sends, then why use transactions?

Exactly right, this is the most important point in this issue.

I had a rethink in the `BatchListenerFailedException` sence. Simple implementation is
- in retry range that seek to reocrds begin offsets
- retry exhaustion that return remaing record exclude recovered records.

File: spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java [hunk 2]
```diff
@@ -137,20 +144,29 @@ public DefaultAfterRollbackProcessor(@Nullable
...
 			BackOff backOff, @Nullable BackOffHandler backOffHandler, @Nullable KafkaOperations<?, ?> kafkaOperations,
 			boolean commitRecovered) {
-
-		super(recoverer, backOff, backOffHandler);
+		super(recoverer, backOff, backOffHandler, new CommonErrorHandler() { });
 		this.kafkaTemplate = kafkaOperations;
 		super.setCommitRecovered(commitRecovered);
 		checkConfig();
 		this.backOff = backOff;
+		this.recoverer = (crs, ex) -> {
```
Comment (Wzy19930507) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java:152]: it's invalid.
recoverer need transaction too
if use DLT,
need producer inTX, consumer inTX, DLT inTX, DLT consumer inTX

**Comment by garyrussell** [comment]
One more time - we cannot support `BatchListenerFailedException` here - the transaction will have rolled back by now so any transactional sends for the records before the failed record will have been ignored; it is not correct to discard those records.

Yes, we could support recovering (sending to DLT) the entire batch, but we can't discard a partial batch here. Even that would have to be an opt-in feature.

**Comment by Wzy19930507** [comment]
Hi, @garyrussell 
Could you do me a favor for build failed?

I didn't modify code at `GlobalEmbeddedKafkaTestExecutionListenerTests#testGlobalEmbeddedKafkaTestExecutionListener`
and ran `./gradlew check` success locally.  

but build failed and following exception is reported
image

**Comment by garyrussell** [comment]
Re-running now; that test is sometimes flaky.

**Comment by Wzy19930507** [comment]
Thanks

**Comment by artembilan** [comment]
@Wzy19930507 ,

please, rebase your branch to the latest `main`.

Then we will start looking into your change to incorporate it into a new version.

Thanks

File: spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java [hunk 3]
```diff
@@ -522,6 +528,7 @@ public Long getIdlePartitionEventInterval() {
 		return this.idlePartitionEventInterval;
 	}
 
+	@Deprecated(since = "3.1")
```
Comment (artembilan) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java:531]: `3.2`

File: spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java [hunk 4]
```diff
@@ -144,6 +139,17 @@ public static void unrecoverableBackOff(BackOff backOff, Map<Thread, BackOffExec
 		}
 	}
 
+	public static long nextBackOff(BackOff backOff, Map<Thread, BackOffExecution> executions) {
```
Comment (artembilan) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java:142]: Not sure if this method supposed to be `public`, but if it is, then it has to have respective Javadoc.

File: spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java [hunk 5]
```diff
@@ -133,6 +133,17 @@ public static boolean doSeeks(List<ConsumerRecord<?, ?>> records, Consumer<?, ?>
 		return skipped.get();
 	}
 
+	public static void doSeeksToBegin(List<ConsumerRecord<?, ?>> records, Consumer<?, ?> consumer,
```
Comment (artembilan) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java:136]: Javadoc, please

File: spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java [hunk 6]
```diff
@@ -135,13 +135,48 @@ void testLatestOnlyNoTx() throws InterruptedException {
 		KafkaTransactionManager tm = new KafkaTransactionManager<>(pf);
 		Producer producer = mock(Producer.class);
 		given(pf.createProducer(any())).willReturn(producer);
-		CountDownLatch latch = new CountDownLatch(1);
 		props.setTransactionManager(tm);
```
Comment (artembilan) [inline spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java:138]: Can we consider to not use deprecated API then?
Although it is not clear why deprecation of that property is the part of this change.
It is really hard to review mixed concerns.

**Review by artembilan — CHANGES_REQUESTED** [review]
Don't we also need to document the feature somehow?

Thanks

File: spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java (hunk 6 above)
Comment (Wzy19930507) [reply spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java:138]: I'll create anthoer issue to this pr

**Review by artembilan — CHANGES_REQUESTED** [review]
Please, also add your name to the `@author` list of all the affected classes.

Thanks

File: spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java [hunk 7]
```diff
@@ -133,6 +133,23 @@ public static boolean doSeeks(List<ConsumerRecord<?, ?>> records, Consumer<?, ?>
 		return skipped.get();
 	}
 
+	/**
+	 * Seek records to begin position, optionally skipping the first.
+	 * @param records the records.
+	 * @param consumer the consumer.
+	 * @param logger a {@link LogAccessor} for seek errors.
```
[the remark this answers is not in the document]
Comment (Wzy19930507) [reply spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java:140]: yes, new method for `DefaultAfterRollbackProcessor.processBatch`

File: spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java [hunk 8]
```diff
@@ -144,6 +139,17 @@ public static void unrecoverableBackOff(BackOff backOff, Map<Thread, BackOffExec
 		}
 	}
 
+	static long nextBackOff(BackOff backOff, Map<Thread, BackOffExecution> executions) {
```
[the remark this answers is not in the document]
Comment (Wzy19930507) [reply spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java:142]: I use `ListenerUtils.nextBackOff` in DefaultAfterRollbackProcessor.processBatch to retry exception

File: spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java [hunk 9]
```diff
@@ -176,6 +186,53 @@ && isCommitRecovered() && this.kafkaTemplate.isTransactional()) {
...
+
+		if (recoverable && isCommitRecovered()) {
+			long nextBackOff = ListenerUtils.nextBackOff(this.backOff, this.backOffs);
+			if (nextBackOff != BackOffExecution.STOP) {
+				SeekUtils.doSeeksToBegin((List) recordList, consumer, this.logger);
+				try {
+					ListenerUtils.stoppableSleep(container, nextBackOff);
+				}
+				catch (InterruptedException e) {
+					Thread.currentThread().interrupt();
```
[the remark this answers is not in the document]
Comment (Wzy19930507) [reply spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java:202]: If new transaction, no rollback is required before `ListenerUtils.stoppableSleep(container, nextBackOff)` in method `processBatch`.
And i'm not sure it makes sense to roll back interrupt exceptions in a nested transaction scenario

File: spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java [hunk 10]
```diff
@@ -118,37 +123,25 @@ void testBatchBackOff() {
...
+		processor.processBatch(consumerRecords, records, consumer, container, illegalState, false, EOSMode.V2);
 		verify(backOff, times(2)).start();
 		verify(execution.get(), times(2)).nextBackOff();
 		processor.clearThreadState();
-		processor.process(records, consumer, container, illegalState, false, EOSMode.V2);
+		processor.processBatch(consumerRecords, records, consumer, container, illegalState, false, EOSMode.V2);
 		verify(backOff, times(3)).start();
 	}
 
-	void testEarlyExitBackOff() {
```
Comment (artembilan) [inline spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java:136]: Why removing this instead of adding `@Test` on the method?

File: spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java [hunk 11]
```diff
@@ -777,12 +785,133 @@ public void accept(ConsumerRecord<?, ?> record, Consumer<?, ?> consumer, Excepti
...
+		verify(afterRollbackProcessor, times(4)).processBatch(any(), any(), any(), any(), captor.capture(), anyBoolean(), any());
+		assertThat(captor.getValue()).isInstanceOf(ListenerExecutionFailedException.class)
+				.extracting(ex -> ((ListenerExecutionFailedException) ex).getGroupId())
+				.isEqualTo(group);
+		verify(afterRollbackProcessor, times(2)).clearThreadState();
+		verify(dlTemplate, times(5)).send(any(ProducerRecord.class));
+		verify(dlTemplate).sendOffsetsToTransaction(
+				eq(Collections.singletonMap(new TopicPartition(topic8, 0), new OffsetAndMetadata(4L))),
+				any(ConsumerGroupMetadata.class));
+		logger.info("Stop testBatchListenerMaxFailures");
```
Comment (artembilan) [inline spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java:907]: Why do we need this info in the logs of the test?

File: spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java [hunk 12]
```diff
@@ -841,6 +970,80 @@ public void testRollbackProcessorCrash() throws Exception {
 		logger.info("Stop testRollbackNoRetries");
 	}
 
+	@SuppressWarnings("unchecked")
+	@Test
+	public void testBatchListenerRecoverAfterRollbackProcessorCrash() throws Exception {
+		logger.info("Start testBatchListenerRollbackNoRetries");
```
Comment (artembilan) [inline spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java:976]: I really don't see reason in this extra logs for the tests...

**Review by artembilan — CHANGES_REQUESTED** [review]

File: spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java (hunk 10 above)
Comment (Wzy19930507) [reply spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java:136]: You are right!

**Review by sobychacko — APPROVED** [review]

**Comment by Wzy19930507** [comment]
@artembilan @garyrussell @sobychacko Thanks for review, this issue could not have been closed without your guidance.
