### PR TITLE
GH-2284: Publish Auth Error Events

### LINKED ISSUE #2284: Publish Event In Container when Authorization/Authentication Exception occurs and retry takes place
Hi @garyrussell  and @artembilan 

I am using spring kafka and i need to do something when kafka connection error happens due to authorization/authentication exception been thrown in the following class - https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

No , i do not want the container to stop , hence i have the authExceptionRetryInterval set. But what i would also like is an application event to be published when this kind of error occurs so i can listen on it and then do something custom. 

Also  , i would also like an event to be published when the connection is successfully restored in the pollAndInvoke() method in the same class. Please let me know your thoughts on the same and if you guys are open to such a change.

### PR DESCRIPTION
**Pull request by danielgentes**
* Added Events for auth failed
and successful retry of auth
* publish of these events
* unit testing

Closes #2284

### CODE REVIEW

File: spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
+/*
+ * Copyright 2018-2022 the original author or authors.
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java:2]: New files only need 2022.

File: spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.springframework.kafka.event;
+
+/**
+ * An event published when authentication or authorization of a consumer fails and is being retried. Contains the triggering throwable.
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java:20]: Please wrap javadocs at 90 chars (code at 120).

File: spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+	 * @param reason the reason.
+	 * @since 3.0
+	 */
+	public ConsumerRetryAuthEvent(Object source, Object container, Reason reason) {
+		super(source, container);
+		this.reason = reason;
+	}
+
+	/**
+	 * Return the reason why the consumer was stopped.
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java:64]: Looks like copy/paste.

Return the reason for the auth failure.

File: spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+	 * @return the reason.
+	 * @since 2.5.8
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java:66]:
```suggestion
	 * @since 2.8.8
```

File: spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthSuccessfulEvent.java [hunk 5]
```diff
@@ -0,0 +1,44 @@
+/*
+ * Copyright 2018-2022 the original author or authors.
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthSuccessfulEvent.java:2]: 2022

**Review by garyrussell — CHANGES_REQUESTED** [review]
Thanks!

Just a few minor nits.

**Comment by danielgentes** [comment]
Hi @garyrussell,
thank you for the review! I addressed the mentioned changed in my latest commit.

File: spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java [hunk 6]
```diff
@@ -529,6 +531,30 @@ private void publishConsumerFailedToStart() {
 		}
 	}
 
+	private void publishRetryAuthEvent(Throwable throwable) {
```
Comment (artembilan) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java:534]: Please, add your name to the `@author` list: you have made some changes to the class, so you deserve some credit.

**Comment by danielgentes** [comment]
Hi @artembilan ,
thanks for the review! I updated the documentation and also made the other changes you suggested.
