### PR TITLE
GH-2862: Add Option to Log Recovery to DLPR

### LINKED ISSUE #2862: Add Option to Log Recovered Record to DeadLetterPublishingRecoverer
See https://stackoverflow.com/questions/77368555/spring-boot-with-kafka-not-logging-exceptions-on-deserialization-when-using-dl/77368770#77368770

### PR DESCRIPTION
**Pull request by Wzy19930507**
Resolves #2862

### CODE REVIEW

File: spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java [hunk 1]
```diff
@@ -400,6 +402,15 @@ public void setSkipSameTopicFatalExceptions(boolean skipSameTopicFatalExceptions
 		this.skipSameTopicFatalExceptions = skipSameTopicFatalExceptions;
 	}
 
+	/**
+	 * Set to true if you want to log recovery record and exception.
+	 * @param logRecoveryRecord true to log record and exception.
+	 * @since 3.1.0
```
Comment (garyrussell) [inline spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java:408]:
```suggestion
	 * @since 3.1
```

File: spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc [hunk 2]
```diff
@@ -729,6 +729,8 @@ Starting with version 2.7, the recoverer checks that the partition selected by t
 If the partition is not present, the partition in the `ProducerRecord` is set to `null`, allowing the `KafkaProducer` to select the partition.
 You can disable this check by setting the `verifyPartition` property to `false`.
 
+Starting with version 3.1.0, set `logRecoveryRecord` to `true` will log recovery record and exception.
```
Comment (garyrussell) [inline spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc:732]:
```suggestion
Starting with version 3.1, setting the `logRecoveryRecord` property to `true` will log the recovery record and exception.
```

**Review by garyrussell — APPROVED** [review]
Thanks; just a couple of minor changes that I will apply before merging.
